const_value = 1

	const MASTER_BALL   ; $01
	const ULTRA_BALL    ; $02
	const GREAT_BALL    ; $03
	const POKE_BALL     ; $04
	const TOWN_MAP      ; $05
	const BICYCLE       ; $06
	const SURFBOARD     ; $07 buggy?
	const SAFARI_BALL   ; $08
	const POKEDEX       ; $09
	const MOON_STONE    ; $0A
	const ANTIDOTE      ; $0B
	const BURN_HEAL     ; $0C
	const ICE_HEAL      ; $0D
	const AWAKENING     ; $0E
	const PARLYZ_HEAL   ; $0F
	const FULL_RESTORE  ; $10
	const MAX_POTION    ; $11
	const HYPER_POTION  ; $12
	const SUPER_POTION  ; $13
	const POTION        ; $14
	const BOULDERBADGE  ; $15
	const CASCADEBADGE  ; $16
SAFARI_BAIT           EQU $15 ; overload
SAFARI_ROCK           EQU $16 ; overload
	const THUNDERBADGE  ; $17
	const RAINBOWBADGE  ; $18
	const SOULBADGE     ; $19
	const MARSHBADGE    ; $1A
	const VOLCANOBADGE  ; $1B
	const EARTHBADGE    ; $1C
	const ESCAPE_ROPE   ; $1D
	const REPEL         ; $1E
	const OLD_AMBER     ; $1F
	const FIRE_STONE    ; $20
	const THUNDER_STONE ; $21
	const WATER_STONE   ; $22
	const HP_UP         ; $23
	const PROTEIN       ; $24
	const IRON          ; $25
	const CARBOS        ; $26
	const CALCIUM       ; $27
	const ZINC          ; $28	; add this for Special Defense
	const RARE_CANDY    ; $29
	const DOME_FOSSIL   ; $2A
	const HELIX_FOSSIL  ; $2B
	const SECRET_KEY    ; $2C
	const BATTLE_PASS   ; $2D	; reuse this unused item as Battle Pass (it is already tagged as a key item)
	const BIKE_VOUCHER  ; $2E
	const LEAF_STONE    ; $2F
	const CARD_KEY      ; $30
	const NUGGET        ; $31
	const PP_UP_2       ; $32
	const POKE_DOLL     ; $33
	const FULL_HEAL     ; $34
	const REVIVE        ; $35
	const MAX_REVIVE    ; $36
	const GUARD_SPEC    ; $37
	const SUPER_REPEL   ; $38
	const MAX_REPEL     ; $39
	const DIRE_HIT      ; $3A
	const COIN          ; $3B
	const FRESH_WATER   ; $3C
	const SODA_POP      ; $3D
	const LEMONADE      ; $3E
	const S_S_TICKET    ; $3F
	const GOLD_TEETH    ; $40
	const X_ATTACK      ; $41
	const X_DEFEND      ; $42
	const X_SPEED       ; $43
	const X_SP.ATK      ; $44
	const X_SP.DEF      ; $45	; added this for Special Defense
	const X_ACCURACY    ; $46	; moved it here so that it follows the other X items
	const COIN_CASE     ; $47
	const OAKS_PARCEL   ; $48
	const ITEMFINDER    ; $49
	const SILPH_SCOPE   ; $4A
	const POKE_FLUTE    ; $4B
	const LIFT_KEY      ; $4C
	const EXP_SHARE     ; $4D
	const OLD_ROD       ; $4E
	const GOOD_ROD      ; $4F
	const SUPER_ROD     ; $50
	const PP_UP         ; $51
	const ETHER         ; $52
	const MAX_ETHER     ; $53
	const ELIXER        ; $54
	const MAX_ELIXER    ; $55
	
	const TINYMUSHROOM	; $56
	const STARDUST		; $57
	const BIG_NUGGET	; $58
	const DUSK_STONE	; $59
	const SUN_STONE		; $5A
	const DAWN_STONE	; $5B
	const ICE_STONE		; $5C
	const SHINY_STONE	; $5D
	const METAL_COAT	; $5E
	const KINGS_ROCK	; $5F
	const LINKING_CORD	; $60
	const ODD_KEYSTONE	; $61
	const ORIGIN_PLATE	; $62 for changing Arceus's Type
	const SKULL_FOSSIL	; $63
	const ARMOR_FOSSIL	; $64
	const JAW_FOSSIL	; $65
	const SAIL_FOSSIL	; $66
	const UPGRADE		; $67
	const DUBIOUS_DISC	; $68
	const GIFT_CARD	    ; $69 can be exchanged for a souvenir in the museum
	const POMEG_BERRY   ; $6A
	const KELPSY_BERRY  ; $6B
	const QUALOT_BERRY  ; $6C
	const HONDEW_BERRY  ; $6D
	const GREPA_BERRY   ; $6E
	const TAMATO_BERRY	; $6F
	const BOTTLE_CAP	; $70
	const GRISEOUS_CORE	; $71 for changing Giratina's Forme
	const GOLDBOTTLECAP	; $72
	const PLACEHOLDER19	; $73
	const PLACEHOLDER20	; $74
	const PLACEHOLDER21	; $75
	const PLACEHOLDER22	; $76
	const PLACEHOLDER23	; $77
	const PLACEHOLDER24	; $78
	const PLACEHOLDER25	; $79
	const PLACEHOLDER26	; $7A
	const NORMAL_TYPE	; $7B
	const FIRE_TYPE		; $7C
	const WATER_TYPE	; $7D
	const ELECTRIC_TYPE	; $7E
	const GRASS_TYPE	; $7F
	const ICE_TYPE		; $80
	const FIGHTING_TYPE	; $81
	const POISON_TYPE	; $82
	const GROUND_TYPE	; $83
	const FLYING_TYPE	; $84
	const PSYCHIC_TYPE	; $85
	const BUG_TYPE		; $86
	const ROCK_TYPE		; $87
	const GHOST_TYPE	; $88
	const DRAGON_TYPE	; $89
	const DARK_TYPE		; $8A
	const STEEL_TYPE	; $8B
	const FAIRY_TYPE	; $8C
	
	const FLOOR_B2F     ; $8D
	const FLOOR_B1F     ; $8E
	const FLOOR_1F      ; $8F
	const FLOOR_2F      ; $90
	const FLOOR_3F      ; $91
	const FLOOR_4F      ; $92
	const FLOOR_5F      ; $93
	const FLOOR_6F      ; $94
	const FLOOR_7F      ; $95
	const FLOOR_8F      ; $96
	const FLOOR_9F      ; $97
	const FLOOR_10F     ; $98
	const FLOOR_11F     ; $99
	const FLOOR_B4F     ; $9A
	                    
	const HM_01         ; $9B
	const HM_02         ; $9C
	const HM_03         ; $9D
	const HM_04         ; $9E
	const HM_05         ; $9F
	const TM_01         ; $A0
	const TM_02         ; $A1
	const TM_03         ; $A2
	const TM_04         ; $A3
	const TM_05         ; $A4
	const TM_06         ; $A5
	const TM_07         ; $A6
	const TM_08         ; $A7
	const TM_09         ; $A8
	const TM_10         ; $A9
	const TM_11         ; $AA
	const TM_12         ; $AB
	const TM_13         ; $AC
	const TM_14         ; $AD
	const TM_15         ; $AE
	const TM_16         ; $AF
	const TM_17         ; $B0
	const TM_18         ; $B1
	const TM_19         ; $B2
	const TM_20         ; $B3
	const TM_21         ; $B4
	const TM_22         ; $B5
	const TM_23         ; $B6
	const TM_24         ; $B7
	const TM_25         ; $B8
	const TM_26         ; $B9
	const TM_27         ; $BA
	const TM_28         ; $BB
	const TM_29         ; $BC
	const TM_30         ; $BD
	const TM_31         ; $BE
	const TM_32         ; $BF
	const TM_33         ; $C0
	const TM_34         ; $C1
	const TM_35         ; $C2
	const TM_36         ; $C3
	const TM_37         ; $C4
	const TM_38         ; $C5
	const TM_39         ; $C6
	const TM_40         ; $C7
	const TM_41         ; $C8
	const TM_42         ; $C9
	const TM_43         ; $CA
	const TM_44         ; $CB
	const TM_45         ; $CC
	const TM_46         ; $CD
	const TM_47         ; $CE
	const TM_48         ; $CF
	const TM_49         ; $D0
	const TM_50         ; $D1
	const TM_51         ; $D2
	const TM_52         ; $D3
	const TM_53         ; $D4
	const TM_54         ; $D5
	const TM_55         ; $D6
	const TM_56         ; $D7
	const TM_57         ; $D8
	const TM_58         ; $D9
	const TM_59         ; $DA
	const TM_60         ; $DB
	const TM_61         ; $DC
	const TM_62         ; $DD
	const TM_63         ; $DE
	const TM_64         ; $DF
	const TM_65         ; $E0
	const TM_66         ; $E1
	const TM_67         ; $E2
	const TM_68         ; $E3
	const TM_69         ; $E4
	const TM_70         ; $E5
	const TM_71         ; $E6
	const TM_72         ; $E7
	const TM_73         ; $E8
	const TM_74         ; $E9
	const TM_75         ; $EA
	const TM_76         ; $EB
	const TM_77         ; $EC
	const TM_78         ; $ED
	const TM_79         ; $EE
	const TM_80         ; $EF
	const TM_81         ; $F0
	const TM_82         ; $F1
	const TM_83         ; $F2
	const TM_84         ; $F3
	const TM_85         ; $F4
	const TM_86         ; $F5
	const TM_87         ; $F6
	const TM_88         ; $F7
	const TM_89         ; $F8
	const TM_90         ; $F9
	const TM_91         ; $FA
	const TM_92         ; $FB
	const TM_93         ; $FC
	const TM_94         ; $FD
	const TM_95         ; $FE
                        
; add constants for some items
POTION_HEAL_AMOUNT         EQU 20
SUPER_POTION_HEAL_AMOUNT   EQU 60
HYPER_POTION_HEAL_AMOUNT   EQU 120
FRESH_WATER_HEAL_AMOUNT    EQU 30
SODA_POP_HEAL_AMOUNT       EQU 50
LEMONADE_HEAL_AMOUNT       EQU 70
ETHER_HEAL_AMOUNT          EQU 10
VITAMIN_BONUS_AMOUNT       EQU 10	; amount of EVs one vitamin gives
