const_value = 1

	const DEX_BULBASAUR  ; 	1
	const DEX_IVYSAUR    ; 	2
	const DEX_VENUSAUR   ; 	3
	const DEX_CHARMANDER ; 	4
	const DEX_CHARMELEON ; 	5
	const DEX_CHARIZARD  ; 	6
	const DEX_SQUIRTLE   ; 	7
	const DEX_WARTORTLE  ; 	8
	const DEX_BLASTOISE  ; 	9
	const DEX_CATERPIE   ; 	10
	const DEX_METAPOD    ; 	11
	const DEX_BUTTERFREE ; 	12
	const DEX_WEEDLE     ; 	13
	const DEX_KAKUNA     ; 	14
	const DEX_BEEDRILL   ; 	15
	const DEX_PIDGEY     ; 	16
	const DEX_PIDGEOTTO  ; 	17
	const DEX_PIDGEOT    ; 	18
	const DEX_RATTATA    ; 	19
	const DEX_RATICATE   ; 	20
	const DEX_SPEAROW    ; 	21
	const DEX_FEAROW     ; 	22
	const DEX_EKANS      ; 	23
	const DEX_ARBOK      ; 	24
	const DEX_PIKACHU    ; 	25
	const DEX_RAICHU     ; 	26
	const DEX_SANDSHREW  ; 	27
	const DEX_SANDSLASH  ; 	28
	const DEX_NIDORAN_F  ; 	29
	const DEX_NIDORINA   ; 	30
	const DEX_NIDOQUEEN  ; 	31
	const DEX_NIDORAN_M  ; 	32
	const DEX_NIDORINO   ; 	33
	const DEX_NIDOKING   ; 	34
	const DEX_CLEFAIRY   ; 	35
	const DEX_CLEFABLE   ; 	36
	const DEX_VULPIX     ; 	37
	const DEX_NINETALES  ; 	38
	const DEX_JIGGLYPUFF ; 	39
	const DEX_WIGGLYTUFF ; 	40
	const DEX_ZUBAT      ; 	41
	const DEX_GOLBAT     ; 	42
	const DEX_CROBAT     ; 	43
	const DEX_ODDISH     ; 	44
	const DEX_GLOOM      ; 	45
	const DEX_VILEPLUME  ; 	46
	const DEX_PARAS      ; 	47
	const DEX_PARASECT   ; 	48
	const DEX_VENONAT    ; 	49
	const DEX_VENOMOTH   ; 	50
	const DEX_DIGLETT    ; 	51
	const DEX_DUGTRIO    ; 	52
	const DEX_MEOWTH     ; 	53
	const DEX_PERSIAN    ; 	54
	const DEX_PSYDUCK    ; 	55
	const DEX_GOLDUCK    ; 	56
	const DEX_MANKEY     ; 	57
	const DEX_PRIMEAPE   ; 	58
	const DEX_ANNIHILAPE ; 	59
	const DEX_GROWLITHE  ; 	60
	const DEX_ARCANINE   ; 	61
	const DEX_POLIWAG    ; 	62
	const DEX_POLIWHIRL  ; 	63
	const DEX_POLIWRATH  ; 	64
	const DEX_ABRA       ; 	65
	const DEX_KADABRA    ; 	66
	const DEX_ALAKAZAM   ; 	67
	const DEX_MACHOP     ; 	68
	const DEX_MACHOKE    ; 	69
	const DEX_MACHAMP    ; 	70
	const DEX_BELLSPROUT ; 	71
	const DEX_WEEPINBELL ; 	72
	const DEX_VICTREEBEL ; 	73
	const DEX_TENTACOOL  ; 	74
	const DEX_TENTACRUEL ; 	75
	const DEX_GEODUDE    ; 	76
	const DEX_GRAVELER   ; 	77
	const DEX_GOLEM      ; 	78
	const DEX_PONYTA     ; 	79
	const DEX_RAPIDASH   ; 	80
	const DEX_SLOWPOKE   ; 	81
	const DEX_SLOWBRO    ; 	82
	const DEX_MAGNEMITE  ; 	83
	const DEX_MAGNETON   ; 	84
	const DEX_MAGNEZONE  ; 	85
	const DEX_FARFETCHD  ; 	86
	const DEX_DODUO      ; 	87
	const DEX_DODRIO     ; 	88
	const DEX_SEEL       ; 	89
	const DEX_DEWGONG    ; 	90
	const DEX_GRIMER     ; 	91
	const DEX_MUK        ; 	92
	const DEX_SHELLDER   ; 	93
	const DEX_CLOYSTER   ; 	94
	const DEX_GASTLY     ; 	95
	const DEX_HAUNTER    ; 	96
	const DEX_GENGAR     ; 	97
	const DEX_ONIX       ; 	98
	const DEX_STEELIX    ; 	99
	const DEX_DROWZEE    ; 	100
	const DEX_HYPNO      ; 	101
	const DEX_KRABBY     ; 	102
	const DEX_KINGLER    ; 	103
	const DEX_VOLTORB    ; 	104
	const DEX_ELECTRODE  ; 	105
	const DEX_EXEGGCUTE  ; 	106
	const DEX_EXEGGUTOR  ; 	107
	const DEX_SPIRITOMB  ; 	108
	const DEX_CUBONE     ; 	109
	const DEX_MAROWAK    ; 	110
	const DEX_HITMONLEE  ; 	111
	const DEX_HITMONCHAN ; 	112
	const DEX_LICKITUNG  ; 	113
	const DEX_KOFFING    ; 	114
	const DEX_WEEZING    ; 	115
	const DEX_RHYHORN    ; 	116
	const DEX_RHYDON     ; 	117
	const DEX_RHYPERIOR  ; 	118
	const DEX_CHANSEY    ; 	119
	const DEX_BLISSEY    ; 	120
	const DEX_TANGELA    ; 	121
	const DEX_TANGROWTH  ; 	122
	const DEX_KANGASKHAN ; 	123
	const DEX_HORSEA     ; 	124
	const DEX_SEADRA     ; 	125
	const DEX_KINGDRA    ; 	126
	const DEX_GOLDEEN    ; 	127
	const DEX_SEAKING    ; 	128
	const DEX_STARYU     ; 	129
	const DEX_STARMIE    ; 	130
	const DEX_MR_MIME    ; 	131
	const DEX_SCYTHER    ; 	132
	const DEX_SCIZOR     ; 	133
	const DEX_JYNX       ; 	134
	const DEX_ELECTABUZZ ; 	135
	const DEX_ELECTIVIRE ; 	136
	const DEX_MAGMAR     ; 	137
	const DEX_MAGMORTAR  ; 	138
	const DEX_PINSIR     ; 	139
	const DEX_TAUROS     ; 	140
	const DEX_MAGIKARP   ; 	141
	const DEX_GYARADOS   ; 	142
	const DEX_LAPRAS     ; 	143
	const DEX_DITTO      ; 	144
	const DEX_EEVEE      ; 	145
	const DEX_VAPOREON   ; 	146
	const DEX_JOLTEON    ; 	147
	const DEX_FLAREON    ; 	148
	const DEX_ESPEON     ; 	149
	const DEX_UMBREON    ; 	150
	const DEX_LEAFEON    ; 	151
	const DEX_GLACEON    ; 	152
	const DEX_SYLVEON    ; 	153
	const DEX_PORYGON    ; 	154
	const DEX_PORYGON2   ; 	155
	const DEX_PORYGON_Z  ; 	156
	const DEX_TOTODILE   ; 	157
	const DEX_CROCONAW   ; 	158
	const DEX_FERALIGATR ; 	159
	const DEX_HOOTHOOT   ; 	160
	const DEX_NOCTOWL    ; 	161
	const DEX_CHINCHOU   ; 	162
	const DEX_LANTURN    ; 	163
	const DEX_TOGEPI     ; 	164
	const DEX_TOGETIC    ; 	165
	const DEX_TOGEKISS   ; 	166
	const DEX_NATU       ; 	167
	const DEX_XATU       ; 	168
	const DEX_MAREEP     ; 	169
	const DEX_FLAAFFY    ; 	170
	const DEX_AMPHAROS   ; 	171
	const DEX_MARILL     ; 	172
	const DEX_AZUMARILL  ; 	173
	const DEX_YANMA      ; 	174
	const DEX_YANMEGA    ; 	175
	const DEX_MURKROW    ; 	176
	const DEX_HONCHKROW  ; 	177
	const DEX_MISDREAVUS ; 	178
	const DEX_MISMAGIUS  ; 	179
	const DEX_GIRAFARIG  ; 	180
	const DEX_FARIGIRAF  ; 	181
	const DEX_GLIGAR     ; 	182
	const DEX_GLISCOR    ; 	183
	const DEX_SNUBBULL   ; 	184
	const DEX_GRANBULL   ; 	185
	const DEX_HERACROSS  ; 	186
	const DEX_SNEASEL    ; 	187
	const DEX_WEAVILE    ; 	188
	const DEX_TEDDIURSA  ; 	189
	const DEX_URSARING   ; 	190
	const DEX_URSALUNA   ; 	191
	const DEX_SWINUB     ; 	192
	const DEX_PILOSWINE  ; 	193
	const DEX_MAMOSWINE  ; 	194
	const DEX_SKARMORY   ; 	195
	const DEX_HOUNDOUR   ; 	196
	const DEX_HOUNDOOM   ; 	197
	const DEX_MUDKIP     ; 	198
	const DEX_MARSHTOMP  ; 	199
	const DEX_SWAMPERT   ; 	200
	const DEX_LOTAD      ; 	201
	const DEX_LOMBRE     ; 	202
	const DEX_LUDICOLO   ; 	203
	const DEX_WINGULL    ; 	204
	const DEX_PELIPPER   ; 	205
	const DEX_RALTS      ; 	206
	const DEX_KIRLIA     ; 	207
	const DEX_GARDEVOIR  ; 	208
	const DEX_GALLADE    ; 	209
	const DEX_SHROOMISH  ; 	210
	const DEX_BRELOOM    ; 	211
	const DEX_WHISMUR    ; 	212
	const DEX_LOUDRED    ; 	213
	const DEX_EXPLOUD    ; 	214
	const DEX_MAKUHITA   ; 	215
	const DEX_HARIYAMA   ; 	216
	const DEX_ARON       ; 	217
	const DEX_LAIRON     ; 	218
	const DEX_AGGRON     ; 	219
	const DEX_MEDITITE   ; 	220
	const DEX_MEDICHAM   ; 	221
	const DEX_CARVANHA   ; 	222
	const DEX_SHARPEDO   ; 	223
	const DEX_NUMEL      ; 	224
	const DEX_CAMERUPT   ; 	225
	const DEX_SHUPPET    ; 	226
	const DEX_BANETTE    ; 	227
	const DEX_DUSKULL    ; 	228
	const DEX_DUSCLOPS   ; 	229
	const DEX_DUSKNOIR   ; 	230
	const DEX_ABSOL      ; 	231
	const DEX_SNORUNT    ; 	232
	const DEX_GLALIE     ; 	233
	const DEX_FROSLASS   ; 	234
	const DEX_SPHEAL     ; 	235
	const DEX_SEALEO     ; 	236
	const DEX_WALREIN    ; 	237
	const DEX_TURTWIG    ; 	238
	const DEX_GROTLE     ; 	239
	const DEX_TORTERRA   ; 	240
	const DEX_CHIMCHAR   ; 	241
	const DEX_MONFERNO   ; 	242
	const DEX_INFERNAPE  ; 	243
	const DEX_STARLY     ; 	244
	const DEX_STARAVIA   ; 	245
	const DEX_STARAPTOR  ; 	246
	const DEX_SHINX      ; 	247
	const DEX_LUXIO      ; 	248
	const DEX_LUXRAY     ; 	249
	const DEX_BUDEW      ; 	250
	const DEX_ROSELIA    ; 	251
	const DEX_ROSERADE   ; 	252
	const DEX_BUIZEL     ; 	253
	const DEX_FLOATZEL   ; 	254
	const DEX_DRIFLOON   ; 	255
	const DEX_DRIFBLIM   ; 	256
	const DEX_BRONZOR    ; 	257
	const DEX_BRONZONG   ; 	258
	const DEX_RIOLU      ; 	259
	const DEX_LUCARIO    ; 	260
	const DEX_SKORUPI    ; 	261
	const DEX_DRAPION    ; 	262
	const DEX_CROAGUNK   ; 	263
	const DEX_TOXICROAK  ; 	264
	const DEX_SNOVER     ; 	265
	const DEX_ABOMASNOW  ; 	266
	const DEX_MUNNA      ; 	267
	const DEX_MUSHARNA   ; 	268
	const DEX_BLITZLE    ; 	269
	const DEX_ZEBSTRIKA  ; 	270
	const DEX_ROGGENROLA ; 	271
	const DEX_BOLDORE    ; 	272
	const DEX_GIGALITH   ; 	273
	const DEX_DRILBUR    ; 	274
	const DEX_EXCADRILL  ; 	275
	const DEX_TYMPOLE    ; 	276
	const DEX_PALPITOAD  ; 	277
	const DEX_SEISMITOAD ; 	278
	const DEX_SEWADDLE   ; 	279
	const DEX_SWADLOON   ; 	280
	const DEX_LEAVANNY   ; 	281
	const DEX_VENIPEDE   ; 	282
	const DEX_WHIRLIPEDE ; 	283
	const DEX_SCOLIPEDE  ; 	284
	const DEX_COTTONEE   ; 	285
	const DEX_WHIMSICOTT ; 	286
	const DEX_PETILIL    ; 	287
	const DEX_LILLIGANT  ; 	288
	const DEX_SANDILE    ; 	289
	const DEX_KROKOROK   ; 	290
	const DEX_KROOKODILE ; 	291
	const DEX_SCRAGGY    ; 	292
	const DEX_SCRAFTY    ; 	293
	const DEX_SOLOSIS    ; 	294
	const DEX_DUOSION    ; 	295
	const DEX_REUNICLUS  ; 	296
	const DEX_JOLTIK     ; 	297
	const DEX_GALVANTULA ; 	298
	const DEX_FERROSEED  ; 	299
	const DEX_FERROTHORN ; 	300
	const DEX_LITWICK    ; 	301
	const DEX_LAMPENT    ; 	302
	const DEX_CHANDELURE ; 	303
	const DEX_AXEW       ; 	304
	const DEX_FRAXURE    ; 	305
	const DEX_HAXORUS    ; 	306
	const DEX_CUBCHOO    ; 	307
	const DEX_BEARTIC    ; 	308
	const DEX_DRUDDIGON  ; 	309
	const DEX_GOLETT     ; 	310
	const DEX_GOLURK     ; 	311
	const DEX_PAWNIARD   ; 	312
	const DEX_BISHARP    ; 	313
	const DEX_DURANT     ; 	314
	const DEX_LARVESTA   ; 	315
	const DEX_VOLCARONA  ; 	316
	const DEX_FENNEKIN   ; 	317
	const DEX_BRAIXEN    ; 	318
	const DEX_DELPHOX    ; 	319
	const DEX_FLETCHLING ; 	320
	const DEX_FLETCHINDER; 	321
	const DEX_TALONFLAME ; 	322
	const DEX_FLABEBE    ; 	323
	const DEX_FLOETTE    ; 	324
	const DEX_FLORGES    ; 	325
	const DEX_SKIDDO     ; 	326
	const DEX_GOGOAT     ; 	327
	const DEX_PANCHAM    ; 	328
	const DEX_PANGORO    ; 	329
	const DEX_SPRITZEE   ; 	330
	const DEX_AROMATISSE ; 	331
	const DEX_SWIRLIX    ; 	332
	const DEX_SLURPUFF   ; 	333
	const DEX_INKAY      ; 	334
	const DEX_MALAMAR    ; 	335
	const DEX_SKRELP     ; 	336
	const DEX_DRAGALGE   ; 	337
	const DEX_CARBINK    ; 	338
	const DEX_PHANTUMP   ; 	339
	const DEX_TREVENANT  ; 	340
	const DEX_NOIBAT     ; 	341
	const DEX_NOIVERN    ; 	342
	const DEX_ROWLET     ; 	343
	const DEX_DARTRIX    ; 	344
	const DEX_DECIDUEYE  ; 	345
	const DEX_CUTIEFLY   ; 	346
	const DEX_RIBOMBEE   ; 	347
	const DEX_MUDBRAY    ; 	348
	const DEX_MUDSDALE   ; 	349
	const DEX_DEWPIDER   ; 	350
	const DEX_ARAQUANID  ; 	351
	const DEX_SALANDIT   ; 	352
	const DEX_SALAZZLE   ; 	353
	const DEX_DRAMPA     ; 	354
	const DEX_YAMPER     ; 	355
	const DEX_BOLTUND    ; 	356
	const DEX_ROLYCOLY   ; 	357
	const DEX_CARKOL     ; 	358
	const DEX_COALOSSAL  ; 	359
	const DEX_IMPIDIMP   ; 	360
	const DEX_MORGREM    ; 	361
	const DEX_GRIMMSNARL ; 	362
	const DEX_SNOM       ; 	363
	const DEX_FROSMOTH   ; 	364
	const DEX_CETODDLE   ; 	365
	const DEX_CETITAN    ; 	366
	const DEX_SNORLAX    ; 	367
	const DEX_OMANYTE    ; 	368
	const DEX_OMASTAR    ; 	369
	const DEX_KABUTO     ; 	370
	const DEX_KABUTOPS   ; 	371
	const DEX_CRANIDOS   ; 	372
	const DEX_RAMPARDOS  ; 	373
	const DEX_SHIELDON   ; 	374
	const DEX_BASTIODON  ; 	375
	const DEX_TYRUNT     ; 	376
	const DEX_TYRANTRUM  ; 	377
	const DEX_AMAURA     ; 	378
	const DEX_AURORUS    ; 	379
	const DEX_AERODACTYL ; 	380
	const DEX_ARTICUNO   ; 	381
	const DEX_ZAPDOS     ; 	382
	const DEX_MOLTRES    ; 	383
	const DEX_DRATINI    ; 	384
	const DEX_DRAGONAIR  ; 	385
	const DEX_DRAGONITE  ; 	386
	const DEX_LARVITAR   ; 	387
	const DEX_PUPITAR    ; 	388
	const DEX_TYRANITAR  ; 	389
	const DEX_BELDUM     ; 	390
	const DEX_METANG     ; 	391
	const DEX_METAGROSS  ; 	392
	const DEX_GIBLE      ; 	393
	const DEX_GABITE     ; 	394
	const DEX_GARCHOMP   ; 	395
	const DEX_DEINO      ; 	396
	const DEX_ZWEILOUS   ; 	397
	const DEX_HYDREIGON  ; 	398
	const DEX_GIRATINA   ;  399
	const DEX_MEWTWO     ; 	400
	const DEX_MEW        ; 	401
	const DEX_ARCEUS     ; 	402

NUM_POKEMON EQU const_value + -1
