const_value = 1

	const BULBASAUR         ; 1
	const IVYSAUR           ; 2
	const VENUSAUR          ; 3
	const CHARMANDER        ; 4
	const CHARMELEON        ; 5
	const CHARIZARD         ; 6
	const SQUIRTLE          ; 7
	const WARTORTLE         ; 8
	const BLASTOISE         ; 9
	const CATERPIE          ; 10
	const METAPOD           ; 11
	const BUTTERFREE        ; 12
	const WEEDLE            ; 13
	const KAKUNA            ; 14
	const BEEDRILL          ; 15
	const PIDGEY            ; 16
	const PIDGEOTTO         ; 17
	const PIDGEOT           ; 18
	const RATTATA           ; 19
	const RATICATE          ; 20
	const SPEAROW           ; 21
	const FEAROW            ; 22
	const EKANS             ; 23
	const ARBOK             ; 24
	const PIKACHU           ; 25
	const RAICHU            ; 26
	const SANDSHREW         ; 27
	const SANDSLASH         ; 28
	const NIDORAN_F         ; 29
	const NIDORINA          ; 30
	const NIDOQUEEN         ; 31
	const NIDORAN_M         ; 32
	const NIDORINO          ; 33
	const NIDOKING          ; 34
	const CLEFAIRY          ; 35
	const CLEFABLE          ; 36
	const VULPIX            ; 37
	const NINETALES         ; 38
	const JIGGLYPUFF        ; 39
	const WIGGLYTUFF        ; 40
	const ZUBAT             ; 41
	const GOLBAT            ; 42
	const CROBAT            ; 43
	const ODDISH            ; 44
	const GLOOM             ; 45
	const VILEPLUME         ; 46
	const PARAS             ; 47
	const PARASECT          ; 48
	const VENONAT           ; 49
	const VENOMOTH          ; 50
	const DIGLETT           ; 51
	const DUGTRIO           ; 52
	const MEOWTH            ; 53
	const PERSIAN           ; 54
	const PSYDUCK           ; 55
	const GOLDUCK           ; 56
	const MANKEY            ; 57
	const PRIMEAPE          ; 58
	const ANNIHILAPE        ; 59
	const GROWLITHE         ; 60
	const ARCANINE          ; 61
	const POLIWAG           ; 62
	const POLIWHIRL         ; 63
	const POLIWRATH         ; 64
	const ABRA              ; 65
	const KADABRA           ; 66
	const ALAKAZAM          ; 67
	const MACHOP            ; 68
	const MACHOKE           ; 69
	const MACHAMP           ; 70
	const BELLSPROUT        ; 71
	const WEEPINBELL        ; 72
	const VICTREEBEL        ; 73
	const TENTACOOL         ; 74
	const TENTACRUEL        ; 75
	const GEODUDE           ; 76
	const GRAVELER          ; 77
	const GOLEM             ; 78
	const PONYTA            ; 79
	const RAPIDASH          ; 80
	const SLOWPOKE          ; 81
	const SLOWBRO           ; 82
	const MAGNEMITE         ; 83
	const MAGNETON          ; 84
	const MAGNEZONE         ; 85
	const FARFETCHD         ; 86
	const DODUO             ; 87
	const DODRIO            ; 88
	const SEEL              ; 89
	const DEWGONG           ; 90
	const GRIMER            ; 91
	const MUK               ; 92
	const SHELLDER          ; 93
	const CLOYSTER          ; 94
	const GASTLY            ; 95
	const HAUNTER           ; 96
	const GENGAR            ; 97
	const ONIX              ; 98
	const STEELIX           ; 99
	const DROWZEE           ; 100
	const HYPNO             ; 101
	const KRABBY            ; 102
	const KINGLER           ; 103
	const VOLTORB           ; 104
	const ELECTRODE         ; 105
	const EXEGGCUTE         ; 106
	const EXEGGUTOR         ; 107
	const SPIRITOMB         ; 108
	const CUBONE            ; 109
	const MAROWAK           ; 110
	const GHOST_MAROWAK     ; 111
	const HITMONLEE         ; 112
	const HITMONCHAN        ; 113
	const LICKITUNG         ; 114
	const KOFFING           ; 115
	const WEEZING           ; 116
	const RHYHORN           ; 117
	const RHYDON            ; 118
	const RHYPERIOR         ; 119
	const CHANSEY           ; 120
	const BLISSEY           ; 121
	const TANGELA           ; 122
	const TANGROWTH         ; 123
	const KANGASKHAN        ; 124
	const HORSEA            ; 125
	const SEADRA            ; 126
	const KINGDRA           ; 127
	const GOLDEEN           ; 128
	const SEAKING           ; 129
	const STARYU            ; 130
	const STARMIE           ; 131
	const MR_MIME           ; 132
	const SCYTHER           ; 133
	const SCIZOR            ; 134
	const JYNX              ; 135
	const ELECTABUZZ        ; 136
	const ELECTIVIRE        ; 137
	const MAGMAR            ; 138
	const MAGMORTAR         ; 139
	const PINSIR            ; 140
	const TAUROS            ; 141
	const MAGIKARP          ; 142
	const GYARADOS          ; 143
	const LAPRAS            ; 144
	const DITTO             ; 145
	const EEVEE             ; 146
	const VAPOREON          ; 147
	const JOLTEON           ; 148
	const FLAREON           ; 149
	const ESPEON            ; 150
	const UMBREON           ; 151
	const LEAFEON           ; 152
	const GLACEON           ; 153
	const SYLVEON           ; 154
	const PORYGON           ; 155
	const PORYGON2          ; 156
	const PORYGON_Z         ; 157
	const TOTODILE          ; 158
	const CROCONAW          ; 159
	const FERALIGATR        ; 160
	const HOOTHOOT          ; 161
	const NOCTOWL           ; 162
	const CHINCHOU          ; 163
	const LANTURN           ; 164
	const TOGEPI            ; 165
	const TOGETIC           ; 166
	const TOGEKISS          ; 167
	const NATU              ; 168
	const XATU              ; 169
	const MAREEP            ; 170
	const FLAAFFY           ; 171
	const AMPHAROS          ; 172
	const MARILL            ; 173
	const AZUMARILL         ; 174
	const YANMA             ; 175
	const YANMEGA           ; 176
	const MURKROW           ; 177
	const HONCHKROW         ; 178
	const MISDREAVUS        ; 179
	const MISMAGIUS         ; 180
	const GIRAFARIG         ; 181
	const FARIGIRAF         ; 182
	const GLIGAR            ; 183
	const GLISCOR           ; 184
	const SNUBBULL          ; 185
	const GRANBULL          ; 186
	const HERACROSS         ; 187
	const SNEASEL           ; 188
	const WEAVILE           ; 189
	const TEDDIURSA         ; 190
	const URSARING          ; 191
	const URSALUNA          ; 192
	const SWINUB            ; 193
	const PILOSWINE         ; 194
	const MAMOSWINE         ; 195
	const SKARMORY          ; 196
	const HOUNDOUR          ; 197
	const HOUNDOOM          ; 198
	const MUDKIP            ; 199
	const MARSHTOMP         ; 200
	const SWAMPERT          ; 201
	const LOTAD             ; 202
	const LOMBRE            ; 203
	const LUDICOLO          ; 204
	const WINGULL           ; 205
	const PELIPPER          ; 206
	const RALTS             ; 207
	const KIRLIA            ; 208
	const GARDEVOIR         ; 209
	const GALLADE           ; 210
	const SHROOMISH         ; 211
	const BRELOOM           ; 212
	const WHISMUR           ; 213
	const LOUDRED           ; 214
	const EXPLOUD           ; 215
	const MAKUHITA          ; 216
	const HARIYAMA          ; 217
	const ARON              ; 218
	const LAIRON            ; 219
	const AGGRON            ; 220
	const MEDITITE          ; 221
	const MEDICHAM          ; 222
	const CARVANHA          ; 223
	const SHARPEDO          ; 224
	const NUMEL             ; 225
	const CAMERUPT          ; 226
	const SHUPPET           ; 227
	const BANETTE           ; 228
	const DUSKULL           ; 229
	const DUSCLOPS          ; 230
	const DUSKNOIR          ; 231
	const ABSOL             ; 232
	const SNORUNT           ; 233
	const GLALIE            ; 234
	const FROSLASS          ; 235
	const SPHEAL            ; 236
	const SEALEO            ; 237
	const WALREIN           ; 238
	const TURTWIG           ; 239
	const GROTLE            ; 240
	const TORTERRA          ; 241
	const CHIMCHAR          ; 242
	const MONFERNO          ; 243
	const INFERNAPE         ; 244
	const STARLY            ; 245
	const STARAVIA          ; 246
	const STARAPTOR         ; 247
	const SHINX             ; 248
	const LUXIO             ; 249
	const LUXRAY            ; 250
	const BUDEW             ; 251
	const ROSELIA           ; 252
	const ROSERADE          ; 253
	const BUIZEL            ; 254
	const FLOATZEL          ; 255
	const DRIFLOON          ; 256
	const DRIFBLIM          ; 257
	const BRONZOR           ; 258
	const BRONZONG          ; 259
	const RIOLU             ; 260
	const LUCARIO           ; 261
	const SKORUPI           ; 262
	const DRAPION           ; 263
	const CROAGUNK          ; 264
	const TOXICROAK         ; 265
	const SNOVER            ; 266
	const ABOMASNOW         ; 267
	const MUNNA             ; 268
	const MUSHARNA          ; 269
	const BLITZLE           ; 270
	const ZEBSTRIKA         ; 271
	const ROGGENROLA        ; 272
	const BOLDORE           ; 273
	const GIGALITH          ; 274
	const DRILBUR           ; 275
	const EXCADRILL         ; 276
	const TYMPOLE           ; 277
	const PALPITOAD         ; 278
	const SEISMITOAD        ; 279
	const SEWADDLE          ; 280
	const SWADLOON          ; 281
	const LEAVANNY          ; 282
	const VENIPEDE          ; 283
	const WHIRLIPEDE        ; 284
	const SCOLIPEDE         ; 285
	const COTTONEE          ; 286
	const WHIMSICOTT        ; 287
	const PETILIL           ; 288
	const LILLIGANT         ; 289
	const SANDILE           ; 290
	const KROKOROK          ; 291
	const KROOKODILE        ; 292
	const SCRAGGY           ; 293
	const SCRAFTY           ; 294
	const SOLOSIS           ; 295
	const DUOSION           ; 296
	const REUNICLUS         ; 297
	const JOLTIK            ; 298
	const GALVANTULA        ; 299
	const FERROSEED         ; 300
	const FERROTHORN        ; 301
	const LITWICK           ; 302
	const LAMPENT           ; 303
	const CHANDELURE        ; 304
	const AXEW              ; 305
	const FRAXURE           ; 306
	const HAXORUS           ; 307
	const CUBCHOO           ; 308
	const BEARTIC           ; 309
	const DRUDDIGON         ; 310
	const GOLETT            ; 311
	const GOLURK            ; 312
	const PAWNIARD          ; 313
	const BISHARP           ; 314
	const DURANT            ; 315
	const LARVESTA          ; 316
	const VOLCARONA         ; 317
	const FENNEKIN          ; 318
	const BRAIXEN           ; 319
	const DELPHOX           ; 320
	const FLETCHLING        ; 321
	const FLETCHINDER       ; 322
	const TALONFLAME        ; 323
	const FLABEBE           ; 324
	const FLOETTE           ; 325
	const FLORGES           ; 326
	const SKIDDO            ; 327
	const GOGOAT            ; 328
	const PANCHAM           ; 329
	const PANGORO           ; 330
	const SPRITZEE          ; 331
	const AROMATISSE        ; 332
	const SWIRLIX           ; 333
	const SLURPUFF          ; 334
	const INKAY             ; 335
	const MALAMAR           ; 336
	const SKRELP            ; 337
	const DRAGALGE          ; 338
	const CARBINK           ; 339
	const PHANTUMP          ; 340
	const TREVENANT         ; 341
	const NOIBAT            ; 342
	const NOIVERN           ; 343
	const ROWLET            ; 344
	const DARTRIX           ; 345
	const DECIDUEYE         ; 346
	const CUTIEFLY          ; 347
	const RIBOMBEE          ; 348
	const MUDBRAY           ; 349
	const MUDSDALE          ; 350
	const DEWPIDER          ; 351
	const ARAQUANID         ; 352
	const SALANDIT          ; 353
	const SALAZZLE          ; 354
	const DRAMPA            ; 355
	const YAMPER            ; 356
	const BOLTUND           ; 357
	const ROLYCOLY          ; 358
	const CARKOL            ; 359
	const COALOSSAL         ; 360
	const IMPIDIMP          ; 361
	const MORGREM           ; 362
	const GRIMMSNARL        ; 363
	const SNOM              ; 364
	const FROSMOTH          ; 365
	const CETODDLE          ; 366
	const CETITAN           ; 367
	const SNORLAX           ; 368
	const OMANYTE           ; 369
	const OMASTAR           ; 370
	const KABUTO            ; 371
	const KABUTOPS          ; 372
	const CRANIDOS          ; 373
	const RAMPARDOS         ; 374
	const SHIELDON          ; 375
	const BASTIODON         ; 376
	const TYRUNT            ; 377
	const TYRANTRUM         ; 378
	const AMAURA            ; 379
	const AURORUS           ; 380
	const AERODACTYL        ; 381
	const ARTICUNO          ; 382
	const ZAPDOS            ; 383
	const MOLTRES           ; 384
	const DRATINI           ; 385
	const DRAGONAIR         ; 386
	const DRAGONITE         ; 387
	const LARVITAR          ; 388
	const PUPITAR           ; 389
	const TYRANITAR         ; 390
	const BELDUM            ; 391
	const METANG            ; 392
	const METAGROSS         ; 393
	const GIBLE             ; 394
	const GABITE            ; 395
	const GARCHOMP          ; 396
	const DEINO             ; 397
	const ZWEILOUS          ; 398
	const HYDREIGON         ; 399
	const GIRATINA_ALTERED	; 400
	const GIRATINA_ORIGIN	; 401
	const MEWTWO            ; 402
	const MEW               ; 403
	const ARCEUS_NORMAL     ; 404
	const ARCEUS_FIRE       ; 405
	const ARCEUS_WATER      ; 406
	const ARCEUS_ELECTRIC   ; 407
	const ARCEUS_GRASS      ; 408
	const ARCEUS_ICE        ; 409
	const ARCEUS_FIGHTING   ; 410
	const ARCEUS_POISON     ; 411
	const ARCEUS_GROUND     ; 412
	const ARCEUS_FLYING     ; 413
	const ARCEUS_PSYCHIC    ; 414
	const ARCEUS_BUG        ; 415
	const ARCEUS_ROCK       ; 416
	const ARCEUS_GHOST      ; 417
	const ARCEUS_DRAGON     ; 418
	const ARCEUS_DARK       ; 419
	const ARCEUS_STEEL      ; 420
	const ARCEUS_FAIRY      ; 421
	
	const FOSSIL_KABUTOPS   ; 422
	const FOSSIL_AERODACTYL ; 423
	const MON_GHOST    		; 424
