ItemNames:
	db "MASTER BALL@"
	db "ULTRA BALL@"
	db "GREAT BALL@"
	db "POKé BALL@"
	db "TOWN MAP@"
	db "BICYCLE@"
	db "?????@"
	db "SAFARI BALL@"
	db "POKéDEX@"
	db "MOON STONE@"
	db "ANTIDOTE@"
	db "BURN HEAL@"
	db "ICE HEAL@"
	db "AWAKENING@"
	db "PARLYZ HEAL@"
	db "FULL RESTORE@"
	db "MAX POTION@"
	db "HYPER POTION@"
	db "SUPER POTION@"
	db "POTION@"
	db "BOULDERBADGE@"
	db "CASCADEBADGE@"
	db "THUNDERBADGE@"
	db "RAINBOWBADGE@"
	db "SOULBADGE@"
	db "MARSHBADGE@"
	db "VOLCANOBADGE@"
	db "EARTHBADGE@"
	db "ESCAPE ROPE@"
	db "REPEL@"
	db "OLD AMBER@"
	db "FIRE STONE@"
	db "THUNDERSTONE@"
	db "WATER STONE@"
	db "HP UP@"
	db "PROTEIN@"
	db "IRON@"
	db "CARBOS@"
	db "CALCIUM@"
	db "ZINC@"
	db "RARE CANDY@"
	db "DOME FOSSIL@"
	db "HELIX FOSSIL@"
	db "SECRET KEY@"
	db "BATTLE PASS@"
	db "BIKE VOUCHER@"
	db "LEAF STONE@"
	db "CARD KEY@"
	db "NUGGET@"
	db "PP UP@"
	db "POKé DOLL@"
	db "FULL HEAL@"
	db "REVIVE@"
	db "MAX REVIVE@"
	db "GUARD SPEC.@"
	db "SUPER REPEL@"
	db "MAX REPEL@"
	db "DIRE HIT@"
	db "COIN@"
	db "FRESH WATER@"
	db "SODA POP@"
	db "LEMONADE@"
	db "S.S.TICKET@"
	db "GOLD TEETH@"
	db "X ATTACK@"
	db "X DEFEND@"
	db "X SPEED@"
	db "X SP.ATK@"
	db "X SP.DEF@"
	db "X ACCURACY@"	; moved it here so that it follows the other X items
	db "COIN CASE@"
	db "OAK's PARCEL@"
	db "ITEMFINDER@"
	db "SILPH SCOPE@"
	db "POKé FLUTE@"
	db "LIFT KEY@"
	db "EXP. SHARE@"
	db "OLD ROD@"
	db "GOOD ROD@"
	db "SUPER ROD@"
	db "PP UP@"
	db "ETHER@"
	db "MAX ETHER@"
	db "ELIXER@"
	db "MAX ELIXER@"
	
	db "TINYMUSHROOM@"
	db "STARDUST@"
	db "BIG NUGGET@"
	db "DUSK STONE@"
	db "SUN STONE@"
	db "DAWN STONE@"
	db "ICE STONE@"
	db "SHINY STONE@"
	db "METAL COAT@"
	db "KING'S ROCK@"
	db "LINKING CORD@"
	db "ODD KEYSTONE@"
	db "ORIGIN PLATE@"
	db "SKULL FOSSIL@"
	db "ARMOR FOSSIL@"
	db "JAW FOSSIL@"
	db "SAIL FOSSIL@"
	db "UPGRADE@"
	db "DUBIOUS DISC@"
	db "GIFT CARD@"
	db "POMEG BERRY@"
	db "KELPSY BERRY@"
	db "QUALOT BERRY@"
	db "HONDEW BERRY@"
	db "GREPA BERRY@"
	db "TAMATO BERRY@"
	db "BOTTLE CAP@"
	db "GRISEOUS CORE@"
	db "GOLDBOTTLECAP@"
	db "NEWITEM19@"
	db "NEWITEM20@"
	db "NEWITEM21@"
	db "NEWITEM22@"
	db "NEWITEM23@"
	db "NEWITEM24@"
	db "NEWITEM25@"
	db "NEWITEM26@"
	db "<NORMAL> NORMAL@"
	db "<FIRE> FIRE@"
	db "<WATER> WATER@"
	db "<ELECTRIC> ELECTRIC@"
	db "<GRASS> GRASS@"
	db "<ICE> ICE@"
	db "<FIGHTING> FIGHTING@"
	db "<POISON> POISON@"
	db "<GROUND> GROUND@"
	db "<FLYING> FLYING@"
	db "<PSYCHIC> PSYCHIC@"
	db "<BUG> BUG@"
	db "<ROCK> ROCK@"
	db "<GHOST> GHOST@"
	db "<DRAGON> DRAGON@"
	db "<DARK> DARK@"
	db "<STEEL> STEEL@"
	db "<FAIRY> FAIRY@"

	db "B2F@"
	db "B1F@"
	db "1F@"
	db "2F@"
	db "3F@"
	db "4F@"
	db "5F@"
	db "6F@"
	db "7F@"
	db "8F@"
	db "9F@"
	db "10F@"
	db "11F@"
	db "B4F@"
