MoveNames::
	db "POUND@"
	db "KARATE CHOP@"
	db "DOUBLESLAP@"
	db "DRAIN PUNCH@"
	db "MEGA PUNCH@"
	db "BULLET PUNCH@"
	db "FIRE PUNCH@"
	db "ICE PUNCH@"
	db "THUNDERPUNCH@"
	db "SCRATCH@"
	db "IRON TAIL@"
	db "METAL CLAW@"
	db "SWORDS DANCE@"
	db "CUT@"
	db "GUST@"
	db "WING ATTACK@"
	db "WHIRLWIND@"
	db "FLY@"
	db "STEEL WING@"
	db "IRON HEAD@"
	db "VENOSHOCK@"
	db "STOMP@"
	db "DOUBLE KICK@"
	db "MEGA KICK@"
	db "JUMP KICK@"
	db "DISARM.VOICE@"
	db "SAND-ATTACK@"
	db "HEADBUTT@"
	db "HORN ATTACK@"
	db "FURY ATTACK@"
	db "TRICK ROOM@"
	db "TACKLE@"
	db "BODY SLAM@"
	db "WRAP@"
	db "TAKE DOWN@"
	db "THRASH@"
	db "DOUBLE-EDGE@"
	db "TAIL WHIP@"
	db "POISON STING@"
	db "BIND@"
	db "PIN MISSILE@"
	db "LEER@"
	db "BITE@"
	db "GROWL@"
	db "ROAR@"
	db "SING@"
	db "SUPERSONIC@"
	db "IRON DEFENSE@"
	db "DISABLE@"
	db "ACID@"
	db "EMBER@"
	db "FLAMETHROWER@"
	db "MIST@"
	db "WATER GUN@"
	db "HYDRO PUMP@"
	db "SURF@"
	db "ICE BEAM@"
	db "BLIZZARD@"
	db "PSYBEAM@"
	db "SCALD@"
	db "AURORA BEAM@"
	db "HYPER BEAM@"
	db "PECK@"
	db "DRILL PECK@"
	db "CRUNCH@"
	db "LOW KICK@"
	db "COUNTER@"
	db "SEISMIC TOSS@"
	db "STRENGTH@"
	db "ABSORB@"
	db "MEGA DRAIN@"
	db "LEECH SEED@"
	db "GROWTH@"
	db "RAZOR LEAF@"
	db "SOLARBEAM@"
	db "POISONPOWDER@"
	db "STUN SPORE@"
	db "SLEEP POWDER@"
	db "PETAL DANCE@"
	db "RAZOR WIND@"
	db "FEINT ATTACK@"
	db "FIRE SPIN@"
	db "THUNDERSHOCK@"
	db "THUNDERBOLT@"
	db "THUNDER WAVE@"
	db "THUNDER@"
	db "ROCK THROW@"
	db "EARTHQUAKE@"
	db "NIGHT SLASH@"
	db "DIG@"
	db "TOXIC@"
	db "CONFUSION@"
	db "PSYCHIC@"
	db "HYPNOSIS@"
	db "EXTRASENSORY@"
	db "AGILITY@"
	db "QUICK ATTACK@"
	db "RAGE@"
	db "TELEPORT@"
	db "NIGHT SHADE@"
	db "MIMIC@"
	db "SCREECH@"
	db "DOUBLE TEAM@"
	db "RECOVER@"
	db "HARDEN@"
	db "MINIMIZE@"
	db "SMOKESCREEN@"
	db "CONFUSE RAY@"
	db "WITHDRAW@"
	db "DEFENSE CURL@"
	db "MEAN LOOK@"
	db "LIGHT SCREEN@"
	db "EXTREMESPEED@"
	db "REFLECT@"
	db "FOCUS ENERGY@"
	db "BIDE@"
	db "METRONOME@"
	db "MIRROR MOVE@"
	db "SELFDESTRUCT@"
	db "SNARL@"
	db "SYNTHESIS@"
	db "FIRE FANG@"
	db "SMOG@"
	db "SLUDGE@"
	db "FISSURE@"
	db "FIRE BLAST@"
	db "WATERFALL@"
	db "CLAMP@"
	db "SWIFT@"
	db "SKULL BASH@"
	db "HAMMER ARM@"
	db "HONE CLAWS@"
	db "AMNESIA@"
	db "PLAY ROUGH@"
    db "ICE FANG@"
	db "HI JUMP KICK@"
	db "GIGA IMPACT@"
	db "DREAM EATER@"
	db "POISON GAS@"
	db "DAZZLINGLEAM@"
	db "LEECH LIFE@"
	db "SHADOW FORCE@"
	db "SKY ATTACK@"
	db "BUBBLE@"
	db "MOONBLAST@"
	db "ICICLE CRASH@"
	db "FLASH@"
	db "FAIRY WIND@"
	db "WOOD HAMMER@"
	db "HEAVY SLAM@"
	db "DRAININGKISS@"
	db "EXPLOSION@"
	db "FURY SWIPES@"
	db "GUILLOTINE@"
	db "REST@"
	db "ROCK SLIDE@"
	db "FORCE PALM@"
	db "TRI ATTACK@"
	db "MAGICAL LEAF@"
	db "SLASH@"
	db "SUBSTITUTE@"
	db "SCARY FACE@"
	db "AQUA TAIL@"
	db "SEED BOMB@"
	db "STRUGGLE@"
	
; new moves
	db "NASTY PLOT@"
	db "DARK PULSE@"
	db "CHARM@"
	db "HYPER VOICE@"
	db "WORK UP@"
	db "FLAME WHEEL@"
	db "FLARE BLITZ@"
	db "FLAME CHARGE@"
	db "OVERHEAT@"
	db "WILL-O-WISP@"
	db "AQUA JET@"
	db "WATER PULSE@"
	db "SPARK@"
	db "THUNDER FANG@"
	db "WILD CHARGE@"
	db "DISCHARGE@"
	db "CHARGE BEAM@"
	db "LEAF BLADE@"
	db "POWER WHIP@"
	db "GIGA DRAIN@"
	db "ENERGY BALL@"
	db "LEAF STORM@"
	db "GRASS KNOT@"
	db "ICE SHARD@"
	db "AVALANCHE@"
	db "POWDER SNOW@"
	db "ICY WIND@"
	db "CROSS CHOP@"
	db "MACH PUNCH@"
	db "CLOSE COMBAT@"
	db "REVENGE@"
	db "BRICK BREAK@"
	db "SUPERPOWER@"
	db "SKY UPPERCUT@"
	db "AURA SPHERE@"
	db "FOCUS BLAST@"
	db "BULK UP@"
	db "POISON FANG@"
	db "CROSS POISON@"
	db "POISON JAB@"
	db "GUNK SHOT@"
	db "SLUDGE BOMB@"
	db "BULLDOZE@"
	db "DRILL RUN@"
	db "MUD SHOT@"
	db "EARTH POWER@"
	db "MUD BOMB@"
	db "AERIAL ACE@"
	db "BRAVE BIRD@"
	db "AIR CUTTER@"
	db "AIR SLASH@"
	db "HURRICANE@"
	db "PSYCHO CUT@"
	db "ZEN HEADBUTT@"
	db "MIRROR COAT@"
	db "PSYSHOCK@"
	db "CALM MIND@"
	db "MEGAHORN@"
	db "BUG BITE@"
	db "X-SCISSOR@"
	db "SIGNAL BEAM@"
	db "BUG BUZZ@"
	db "STRUGGLE BUG@"
	db "SILVER WIND@"
	db "ROCK BLAST@"
	db "ROCK TOMB@"
	db "STONE EDGE@"
	db "POWER GEM@"
	db "ANCIENTPOWER@"
	db "PHANTOMFORCE@"
	db "SHADOW PUNCH@"
	db "SHADOW CLAW@"
	db "SHADOW SNEAK@"
	db "SHADOW BALL@"
	db "OMINOUS WIND@"
	db "HEX@"
	db "OUTRAGE@"
	db "DRAGON CLAW@"
	db "DRAGON RUSH@"
	db "TWISTER@"
	db "DRAGONBREATH@"
	db "DRAGON PULSE@"
	db "DRACO METEOR@"
	db "DRAGON DANCE@"
	db "FLASH CANNON@"
	db "SUCKER PUNCH@"
	db "BABYDOLLEYES@"
	db "SIGNATURE 1@"
	db "SIGNATURE 2@"

SignatureMoveNames::
	db "HYPER FANG@"
	db "SUPER FANG@"
	db "PAY DAY@"
	db "SLAM@"
	db "EGG BOMB@"
	db "COMET PUNCH@"
    db "SPIKE CANNON@"
    db "CONSTRICT@"
    db "BARRAGE@"
    db "DIZZY PUNCH@"
	db "VICEGRIP@"
	db "DOUBLE HIT@"
	db "RAGING BULL@"
	db "HORN DRILL@"
    db "SONICBOOM@"
    db "BOOMBURST@"
    db "JUDGMENT@"
    db "CONVERSION@"
	db "TRANSFORM@"
	db "SLACK OFF@"
	db "MORNING SUN@"
	db "SOFTBOILED@"
    db "SWEET SCENT@"
	db "SHARPEN@"
    db "HOWL@"
    db "GLARE@"
    db "LOVELY KISS@"
    db "SPLASH@"
    db "FIRE LASH@"
    db "HEAT CRASH@"
    db "HEAT WAVE@"
    db "LAVA PLUME@"
    db "FLAME BURST@"
    db "MYSTICALFIRE@"
    db "CRABHAMMER@"
	db "LIQUIDATION@"
    db "WAVE CRASH@"
	db "BUBBLEBEAM@"
    db "MUDDY WATER@"
    db "ELECTROWEB@"
    db "SHOCK WAVE@"
    db "LEAFAGE@"
    db "BULLET SEED@"
    db "HORN LEECH@"
    db "PETALBLIZARD@"
    db "VINE WHIP@"
    db "SPORE@"
    db "COTTON SPORE@"
    db "GRASSWHISTLE@"
    db "ICICLE SPEAR@"
    db "ICE SPINNER@"
    db "SHEER COLD@"
    db "HAZE@"
    db "ROLLING KICK@"
    db "SUBMISSION@"
    db "ARM THRUST@"
    db "LOW SWEEP@"
    db "POWERUPPUNCH@"
	db "VITAL THROW@"
    db "VACUUM WAVE@"
    db "POISON TAIL@"
    db "SLUDGE WAVE@"
	db "ACID ARMOR@"
    db "BONE CLUB@"
    db "BONEMERANG@"
    db "HEADLONGRUSH@"
    db "MUD SLAP@"
	db "ACROBATICS@"
    db "FEATHERDANCE@"
    db "PSYWAVE@"
    db "PSYSTRIKE@"
    db "TWIN BEAM@"
    db "COSMIC POWER@"
	db "BARRIER@"
    db "MEDITATE@"
    db "KINESIS@"
    db "TWINEEDLE@"
    db "LUNGE@"
	db "STEAMROLLER@"
    db "POLLEN PUFF@"
	db "STRING SHOT@"
	db "QUIVER DANCE@"
    db "HEAD SMASH@"
    db "ROCK WRECKER@"
    db "ROCK POLISH@"
    db "ASTONISH@"
	db "LICK@"
    db "DRAGON TAIL@"
    db "DUAL CHOP@"
    db "BREAK SWIPE@"
    db "DRAGON RAGE@"
    db "METEOR MASH@"
	db "SMART STRIKE@"
    db "MIRROR SHOT@"
	db "METAL SOUND@"
    db "FALSE SURNDR@"
    db "FAKE TEARS@"
    db "SPIRIT BREAK@"
    db "MOONLIGHT@"
	db "SWEET KISS@"
